### ISSUE TITLE
Create solution and project

### ISSUE THREAD

**Issue by alexatrhea** [RHEAGROUP/DEHP-ECOSIMPRO#1]
A new WPF solution for EcosimPro adapter.

**Comment by lxatrhea** [comment]
- Reference to CLA
- LGPL open source
- File headers
- Readme
- Wiki
- .sln / *.csproj
- Test projects
- CI/CD (incl Sonarcube)
- Code of Conduct (copy from SDK)
- Github Contributing template (copy from SDK)
- Github PR template (copy from SDK)
